spring:
  kafka:
    consumer:
      group-id: kafka-intro
      bootstrap-servers: kafka:9092
    producer:
      bootstrap-servers: kafka:9092
logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: DEBUG
