spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: kafka-intro

---
spring:
  profiles: debug

logging:
  level:
    org.springframework.kafka: DEBUG
    org.apache.kafka: DEBUG
